### ISSUE TITLE
Code formatting inside the generated aliases

### ISSUE THREAD

**Issue by failable** [ibraheemdev/derive-alias#1]
Hi, currently the struct definition inside the generated alias body can not be formatted by `rustfmt`. Is there a way to fix this? Thanks.

**Comment by ibraheemdev** [comment]
Sorry, that's a limitation of rustfmt's macro formatting not of this crate. I would suggest using the [`macro_rules_attribute`](https://docs.rs/macro_rules_attribute/0.2.0/macro_rules_attribute/macro.derive_alias.html) crate for it's derive macro instead.

**Comment by failable** [comment]
@ibraheemdev Thanks for you suggestion!
